server:
  port: 8761

eureka:
  instance:
    # Default values in org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${server.port}
    hostname: localhost
  client:
    # Default values in org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
    registerWithEureka: false #单节点服务注册中心无需注册或检索服务
    fetchRegistry: false #单节点服务注册中心无需注册或检索服务
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Default values in org.springframework.cloud.netflix.eureka.server.EurekaServerConfigBean
    waitTimeInMsWhenSyncEmpty: 30000
    renewalPercentThreshold: 0.49
    renewalThresholdUpdateIntervalMs: 60000
    #自我保护，单机测试时容易产生服务无法及时踢出的问题，本地开发时关闭
    enableSelfPreservation: true

logging:
  level:
    root: INFO
